#+TITLE: A Simple Shell Implementation
#+AUTHOR: 陈一鸣

* Abstract
This is a simple shell implementation. The basic functions are defined in
/Operating System Concepts Ninth Edition/[fn:1], Chapter 3, Project 1. Which
means, this shell can execute one single command given by user, can run commands
in the background and have some basic history methods. And I borrowed some
concepts from the xv6's shell implementation and added readline library to give
a more advanced input experience for users.
* Project Requiements
In my humble opinion, there are three different kinds of shells baced on what
kind of commands they can handle.

1. Shells that can execute one single command given by user.

   #+BEGIN_SRC sh
     ls
     cd ..
     mv
     mkdir
     ls &
     history
     !!
     !N
   #+END_SRC

2. Shells that can execute multiple commands in one line, pipeline commands and etc.

   #+BEGIN_SRC sh
     ls && cd ..
     ls & cd ..
     ls -all | grep
   #+END_SRC

3. Shells that can execute shell scripts. Such as bash, zsh, fish and etc.

According to the text book, this project only needs us to implement the first
one and has two parts. And the shell needs some basic error handling functions
for sure.

- Part 1 ::
     Use =fork()=, =execvp()= and =wait()= to fork a child progress, execute the
     command specified by user and determine whether to wait for it by the '&'
     character.
- Part 2 ::
     Add a command named =history=, which can list the command history as the
     following example showed:

     #+BEGIN_EXAMPLE
       6 ps
       5 ls -l
       4 top
       3 cal
       2 who
       1 date
     #+END_EXAMPLE

     Support two methods for retrieving commands from the history:

     #+BEGIN_SRC sh
       !! # Execute the last command
       !N # Execute the Nth command
     #+END_SRC
* Basic Design
I thought the later two kinds of shell are beyond my personal ability. Since
they all needs some kind of syntax analysis knowledge. So I decided to just
implement Part 1 and 2 with some enhancements.
** Type Definitions
As we all know, C language is not a Object-Oriented Programming Language. But we
can still use =struct= to get some features, such as inheritance and
polymorphism. I learned this from the shell implement in xv6.

So I made several structs for commands from the very first time.

1. =cmd=, the basic struct which contains command type and a boolean variable
   indicates whether this command includes a '&' character.

   #+BEGIN_SRC c
     struct cmd {
         int type;
         int include_ampersand;
     };
   #+END_SRC

2. =execCmd=, the most common command. Such as =mkdir=, =mv=, =cp= and etc.
   Which we can directly call =execvp= to execute this command.

   #+BEGIN_SRC c
     struct execCmd {
         int type;
         int include_ampersand;
         char *args[MAX_LINE / 2 + 1];
     };
   #+END_SRC

3. =exitCmd=, this command type is for a specific command named =exit=, which
   will set the =should_run= variable to 0 and thus cause the osh program exit.

   #+BEGIN_SRC c
     struct exitCmd {
         int type;
         int include_ampersand;
         char *args[MAX_LINE / 2 + 1];
     };
   #+END_SRC

4. =cdirCmd=, this command type is for a specific command named =cd=, which will
   change the working directory of the current osh progress. If we create a
   child thread and change the working directory in the child progress, it will
   not affect the parent thread. So we need to make =cd= a built-in command of
   the osh.

   #+BEGIN_SRC c
     struct cdirCmd {
         int type;
         int include_ampersand;
         char *args[MAX_LINE / 2 + 1];
     };
   #+END_SRC

5. =execHisCmd=, this command type is for commands related to command history.
   Such as =history=, =!!= and =!N=.

   #+BEGIN_SRC c
     struct execHisCmd {
         int type;
         int include_ampersand;
         char *args[MAX_LINE / 2 + 1];
     };
   #+END_SRC

I have to admit that I didn't use the most power of polymorphism in this
project. As you can see, these types are almost the same. But it's convenient
for us to add some more complicated commands such as pipeline commands if we
make some prepare for them.

And I added one more struct for history queue.

- =history=, it stores the current history's index (using =count=), and a array
  of input commands so that user can call them using history commands.

  #+BEGIN_SRC c
    struct history {
        int count;
        char bufs[HISTORY_CAPACITY][MAX_LINE];
    };
  #+END_SRC
** Functions
*** Command Functions
- =getCmd=, this is the input function, which handles user's one line input and
  save it as a string. Since I added GNU Readline library as the input library
  after I finished all the basic functions. So I have two different
  implementation for this function. One is implemented by myself[fn:2], another one
  uses the readline library[fn:3].

  #+BEGIN_SRC c
    int getCmd(char **buf);
  #+END_SRC

- =saveCmd=, this function saves the input string into the history queue.

  #+BEGIN_SRC c
    int saveCmd(char *buf, struct history *his);
  #+END_SRC

- =parseCmd=, this function parses the input string and returns a =cmd= pointer
  which points to a =cmd= contains cmd type and cmd args.

  #+BEGIN_SRC c
    struct cmd* parseCmd(char *buf);
  #+END_SRC

- =runCmd=, this function runs the command according to the cmd type.

  #+BEGIN_SRC c
    int runCmd(struct cmd* cmd, int *should_run, struct history *his);
  #+END_SRC
*** History Functions
- =getHistory=, this function returns the N^{th} commands according to the given
  =index=. And if the index is out of range, it will return 0.

  #+BEGIN_SRC c
    char* getHistory(struct history *his, int index);
  #+END_SRC

- =printHistory=, this function handles the =history= command. It print out the
  last 10 commands user has used.

  #+BEGIN_SRC c
    int printHistory(struct history *his);
  #+END_SRC

- =execHistory=, this function handles the =!N= command and the =!!= command. It
  will print the N^{th} command (or the last command if the given command is
  =!!=) and execute it.

  #+BEGIN_SRC c
    int execHistory(struct execHisCmd *execHisCmd, struct history *his, int *should_run);
  #+END_SRC
*** Helper Functions
These are some helper functions used in =parseCmd=.
- =isWhitespace=, return 1 if the given char is a whitespace, return true otherwise.

  #+BEGIN_SRC c
    int isWhitespace(char ch);
  #+END_SRC

- =handleAmpersand=, return 1 if the given arg is a '=&=' or its last character is
  a '=&=', and set it to '=\0='. Return 0 otherwise.

  #+BEGIN_SRC c
    int handleAmpersand(char *arg);
  #+END_SRC
* Footnotes

[fn:3] [[https://github.com/dsdshcym/OS_Projects/blob/readline_input/Unix_Shell_and_History_Feature/osh.c#L129-L139][getCmd uses readline library]]

[fn:2] [[https://github.com/dsdshcym/OS_Projects/blob/normal_input/Unix_Shell_and_History_Feature/osh.c#L127-L138][My original getCmd]]

[fn:1] Galvin P B, Gagne G, Silberschatz A. Operating system concepts[M]. John Wiley & Sons, Inc., 2013.
